version: 2.1
executors:
  node_lts: # declares a reusable executor
    docker:
      - image: &NODE_VERSION node:14.15.3
    working_directory: ~/repo
jobs:
  build:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v14-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-v14-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      - run: yarn lint
  test:
    executor: node_lts
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-v14-{{ checksum "yarn.lock" }}

      - run: yarn install

      - run: mkdir ~/jest

      - run: JEST_JUNIT_OUTPUT_DIR=~/jest JEST_JUNIT_OUTPUT_NAME=test-unit-junit.xml yarn test --ci --reporters=default --reporters=jest-junit --maxWorkers=2

      - store_test_results:
          path: ~/jest
  test-integration:
    docker:
      - image: *NODE_VERSION
      - image: circleci/postgres:12.5
        environment:
          POSTGRES_USER: node-api
          POSTGRES_PASSWORD: our-secret
          POSTGRES_DB: ts-node-api
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-v12-{{ checksum "yarn.lock" }}

      - run: yarn install

      - run: mkdir ~/jest

      - run: JEST_JUNIT_OUTPUT_DIR=~/jest JEST_JUNIT_OUTPUT_NAME=test-int-junit.xml yarn test:int --ci --reporters=default --reporters=jest-junit

      - store_test_results:
          path: ~/jest
workflows:
  version: 2
  complete:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-integration:
          requires:
            - build
